FactoryGirl.define do
  factory :observation do
	  route_number 									"9001"
		year													"1986"
		observation_place_number			"1"
		observer_id										"8000"
		municipal_code								"LOHJA"
		nnn_coordinate								"667"
		eee_coordinate								"333"
		biotope_class									"3"
		route_representative_class		"1"
		spot_observation_place_count	"18"
		roaming_observation_place_count "0"
		observation_place_name				"JUSOLANLAMPI"
		first_observation_date				"1986-05-11"
		second_observation_date				nil
		first_observation_hour				"7"
		first_observation_duration		"5"
		second_observation_hour		 	 	"0"
		second_observation_duration		"0"
		water_system_area							"2.0"
		place_area										"2.0"
		area_covers_fully							"1"
		covering_area_beginning				nil
		covering_area_end							nil
		spot_counting									true
		binoculars										false
		boat													false
		anapla												"0"
		anacre												"0"
		anaacu												"0"
		anacly												"0"
		aytfer												"0"
		buccla												"0"
		mermer												"0"
		fulatr												"0"
		gavarc												"0"
		podcri												"0"
		podgri												"0"
		podaur												"0"
		cygcyg												nil
		ansfab												nil
		bracan												nil
		anapen												"0"
		anaque												"0"
		aytful												"0"
		melfus												"0"
		merser												"0"
		meralb												nil
		gullbirds											true
		larmin												"0"
		larrid												"0"
		larcan												"0"
		stehir												"0"
		waders_eurasian_bittern				true
		galgal												"0"
		trigla												nil
		trineb												nil
		trioch												nil
		acthyp												"0"
		numarq												nil
		vanvan												nil
		botste												nil
		passerine											true
		embsch												"0"
		acrsch												"0"
	end
end
